### ISSUE TITLE
Missing attribute in Postman

### ISSUE THREAD

**Issue by misterfifi1** [infamousjoeg/CyberArk-RESTAPI#1]
Hi, 

Thanks, for your documentation, I found a missing point in the Application/Add authentication method: 
[limk](https://documenter.getpostman.com/view/998920/cyberark-rest-api-v10-public/2QrXnF#653178c2-06c2-8fc1-39c1-9327e5897244)

Following the documentation, it is also possible to add an IP address.

`{
    "authentication":
    {
        "AuthType":machineAddress,
        "AuthValue":"<machine address>"
    }
}`

Regards,

**Comment by infamousjoeg** [comment]
Sorry it took so long to finally resolve the issue, but thanks for logging it!

I just added those types to "AuthType" and "AuthValue" in the Application -> Add Authentication endpoint.

🎊 Keep them coming! 🎊
