### ISSUE TITLE
403 error when trying to connect through postman

### ISSUE THREAD

**Issue by deanhinson** [infamousjoeg/CyberArk-RESTAPI#2]
I am trying to use postman to access the Cyber Ark API. I was following your getting start with postman PDF. I used the Post Cyber Ark Authentication command because that is the same way as when I use the web page UI. I get a 403 error:
"ErrorCode": "PASWS013E",
"ErrorMessage": "Failed to logon. Reason: Authentication failure for User XXX

Using these same credentials I can log onto the Vault through the web page UI. My credentials are vault admin and have full access. 

Server Info:

Windows 2012 R2
Cyber Ark 9.9.5.1

**Comment by Sarvesh2011** [comment]
Hey@deanhinson

How did you resolved it?

**Comment by mohnishkumar2006** [comment]
how this is resolved
